---
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      # hostname: changedetection
      volumes:
        - ./data:/datastore

      environment:
  #        Log levels are in descending order. (TRACE is the most detailed one)
  #        Log output levels: TRACE, DEBUG(default), INFO, SUCCESS, WARNING, ERROR, CRITICAL
  #      - LOGGER_LEVEL=DEBUG

       - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
       # Hides the `Referer` header so that monitored websites can't see the changedetection.io hostname.
       - HIDE_REFERER=true
       # Default number of parallel/concurrent fetchers
       - FETCH_WORKERS=2
      restart: unless-stopped
      # Comment out ports: when using behind a reverse proxy , enable networks: etc.
      ports:
        - 5000:5000
      depends_on:
          playwright-chrome:
              condition: service_started
      security_opt:
        - no-new-privileges:true
     # Used for fetching pages via Playwright+Chrome where you need Javascript support.
     # RECOMMENDED FOR FETCHING PAGES WITH CHROME
    playwright-chrome:
        hostname: playwright-chrome
        image: dgtlmoon/sockpuppetbrowser:latest
        cap_add:
            - SYS_ADMIN
  # SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
        restart: unless-stopped
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1024
            - SCREEN_DEPTH=16
            - MAX_CONCURRENT_CHROME_PROCESSES=5
        security_opt:
            - no-new-privileges:true
# volumes:
#   changedetection-data:
