---
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    # networks:
    #  - internal

  app:
    hostname: nextcloud
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      # - ./nextcloud-data:/var/www/html
      - ./appconfig-data:/var/www/html
      # Mapping the user data directory from the container onto separate directory.
      # Needs to create and  chown www-data:www-data users-data directory prior starting the containers
      # - ./users-data:/var/www/html/data
      - ./users-data:/opt/nextcloud-data
      # - /mnt/shares/NextCloud/users-data:/opt/nextcloud-data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.home.lab
      - OVERWRITECLIURL=https://cloud.home.lab/
      - OVERWRITEPROTOCOL=https
      - VIRTUAL_HOST=cloud.home.lab
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=/opt/nextcloud-data # moving the user data from /var/html to this directory
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
    ports:
      - 80:80
    # networks:
    #  - internal
    # - ext-mivoaka

  redis:
    image: redis:alpine
    restart: unless-stopped
    # networks:
    #  - internal
    volumes:
      - ./redis-data:/data

networks:
  internal:
    driver: bridge
    internal: true
  ext-mivoaka:
    external: true

# volumes:
#   db:
#   nextcloud:

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt # put admin username in this file
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username in this file
