---
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ./assets:/www/assets
      # ports:
      #- 8080:8080 # to be used if running standalone
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    restart: unless-stopped
    networks:
      - to-proxy

networks:
  to-proxy:
    name: proxy-backend
    external: true
